### PR TITLE
Support bytestring-0.11

### PR DESCRIPTION
**Pull request by Bodigrim**

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
@Bodigrim The next is this library. Should I add `base >= 4.9` to all metadata on Hackage?

**Comment by Bodigrim** [comment]
We need somehow avoid an unbuildable combination of `base-4.8` and `bytestring-0.11`. I'd say that revising with `bytestring < 0.11` is less controversial than with `base >= 4.9`, but whatever floats your boat. If you are reluctant to make a new release, you can, for instance, revise everything except `logger-3.0.2` with `bytestring < 0.11`, but revise `logger-3.0.2` with `base >= 4.9`.

**Comment by kazu-yamamoto** [comment]
I will do anything to help users if I'm convinced. :-) Does the follow work well?

- Releasing new fast-logger and wai-logger with `base > 4.9`.
- Modifying all old metadata with `bytestring < 0.11`.

**Comment by Bodigrim** [comment]
Yes, sounds good. You probably do not need to revise existing releases of `wai-logger`: once `fast-logger` has necessary bounds in place, `wai-logger` is protected from unbuildable configurations as well.

**Comment by kazu-yamamoto** [comment]
@Bodigrim Done for `fast-logger`. Please check. If OK, the next turn is `http2`.

**Comment by Bodigrim** [comment]
All good, thanks!

**Pull request closed without merging**
