### PR TITLE
Fix#85

### PR DESCRIPTION
**Pull request by winterland1989**
Fix `bracket` version and single file version clean up. regard to the `LogFile` -> `LogFileNoRotate` change, i have fix it in wai-logger already, i think what we should do here is bump fast-logger to v2.5.0 and release was-logger 2.3.0 which only work with new version fast-logger. what do you think?

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
Where can I find the change of `LogFile`?

**Comment by kazu-yamamoto** [comment]
If we don't break backward compatibility and just add new APIs, the major versions should be the same.

**Comment by kazu-yamamoto** [comment]
> Where can I find the change of LogFile?

I did this by myself.

**Comment by kazu-yamamoto** [comment]
@snoyberg We are discussing the next version numbers:

- fast-logger 2.4.5 or 2.5.0
- wai-logger 2.2.6 or 2.3.0

`LogType` was transferred from wai-logger to fast-logger and wai-logger re-exports it. No breaking changes. Only new APIs are added. So, I would take the minor version up.

However, I noticed that `wai-extra` needs this change:

```
diff --git a/wai-extra/wai-extra.cabal b/wai-extra/wai-extra.cabal
index a77ae2e..3906bc6 100644
--- a/wai-extra/wai-extra.cabal
+++ b/wai-extra/wai-extra.cabal
@@ -95,8 +95,8 @@ Library
                    , text                      >= 0.7
                    , case-insensitive          >= 0.2
                    , data-default-class
-                   , fast-logger               >= 2.1      && < 2.5
-                   , wai-logger                >= 2.0      && < 2.3
+                   , fast-logger               >= 2.4.5    && < 2.5
+                   , wai-logger                >= 2.2.6      && < 2.3
                    , ansi-terminal
                    , resourcet                 >= 0.4.6    && < 1.2
                    , void                      >= 0.5
```

Without this, `LogType` is ambiguous in some cases.

Is this acceptable? Or should we change the major versions?

**Comment by snoyberg** [comment]
I'm fine with a minor version bump, that's what the PVP technically
requires in this case.

**Comment by winterland1989** [comment]
Let's do this！

**Comment by kazu-yamamoto** [comment]
HackageDB refuses fast-logger:

```
Uploading fast-logger-2.4.5.tar.gz...
Error: fast-logger-2.4.5.tar.gz: 400 Bad Request
```

Why? `cabal check` does not report any errors...

**Comment by kazu-yamamoto** [comment]
OK. Done.

I'm using a different PC today. My old password of HackageDB was cached in this machine...

**Pull request merged**
