### PR TITLE
update cabal file

### PR DESCRIPTION
**Pull request by mimi1vx**
bytestring-builder is fully integrated in newer versions of bytestring

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
It seems to me that, with this patch, bytestring 0.10.4.0 or higher is installed for GHC 7.6.x which provides bytestring 0.10.0.2. That would make dependency hell. To avoid this, users need to specify the new flag.

bytestring-builder is redundant for GHC 7.8.x or later but it is not harmful because it is compiled as an empty module in that case. So, I would like to stay with the current code.

Am I missing something?

**Comment by mimi1vx** [comment]
empty package of bytestring builder cause dependecy problem in RPM based distributions like fedora/opensuse

better is user decide if needs using of old bytestring

**Comment by snoyberg** [comment]
If the issue is that RPM needs to disable this package, I'd recommend setting `manual: True`. @kazu-yamamoto is right that, as set up now, there's a strong possibility that `cabal-install` will decide to install a new version of bytestring on users' systems, resulting in dependency complications.

**Comment by mimi1vx** [comment]
@snoyberg  using of ghc 7.6 and lower in time is smaller and smaller , + this solution works in other packages without any problems

**Comment by bergmark** [comment]
On second glance, isn't a better solution to add bytestring-builder when needed?

```
Flag new-bytestring
  default: True
  manual: False

if flag(new-bytestring)
  build-depends: bytestring >= 0.10.4
else
  build-depends: bytestring < 0.10.4, bytestring-builder
```

But I also think fedora/opensuse should allow empty packages, several other packages also do this so fast-logger can't be the only one affected.

**Comment by kazu-yamamoto** [comment]
Now I understand this issue. Using bytestring-builder is a right way. No conditional support is necessary. If people have a problem, they should upgrade their blaze-builder to 0.4 or later. That's all.

I would close this issue.

**Pull request closed without merging**
