### PR TITLE
Fix #204 Remove Safe if directory >= 1.3.8

### LINKED ISSUE #204: fast-logger fails to build with directory >=1.3.8
Building fast-logger with directory >>=1.3.8 fails, due to System.Directory module no more is Safe Haskell.

directory >=1.3.8 is necessary for packages utilizing support for Abstract filepath proposal AFPP.

### PR DESCRIPTION
**Pull request by mpilgrem**

### CODE REVIEW

**Comment by hasufell** [comment]
Any movement here?

**Comment by mpilgrem** [comment]
@kazu-yamamoto, may I bring this pull request to your attention? This is blocking Stack from adopting the 'abstract filepath proposal' (AFPP).

**Review by kazu-yamamoto — APPROVED** [review]
LGTM

**Comment by kazu-yamamoto** [comment]
I'm very sorry for missing this PR.
I will release a new version ASAP.

**Pull request merged**
