### PR TITLE
When nlen > size, make bigger buffer #102

### PR DESCRIPTION
**Pull request by snoyberg**

### CODE REVIEW

**Comment by snoyberg** [comment]
I implemented a truly crazy idea for ensuring only one `write` occurs at once, see: f528e4d1b0a0bd9c71967c7387179b780b728308.

BTW, I hope you're enjoying ICFP Kazu, I miss seeing you there. No rush on getting to this, we're working around this in our application right now.

**Comment by kazu-yamamoto** [comment]
Sorry for the delay. I have merged your PR. I have no experience on this issue. So, let's release this version then see what will happen in the field.

**Comment by kazu-yamamoto** [comment]
I have released a new version.

**Comment by snoyberg** [comment]
Thank you!

**Pull request merged**
