### PR TITLE
Callstack based logging

### PR DESCRIPTION
**Pull request by alexbiehl**
@snoyberg as discussed in #93. 

I haven't written comments on the functions. Lets see if you like it first.

### CODE REVIEW

**Comment by snoyberg** [comment]
LGTM! 👍

**Comment by alexbiehl** [comment]
I added some comments and squashed the commits.

**Comment by snoyberg** [comment]
This looks good. I've asked some colleagues to review as well, since others on my team have more CallStack experience than I do. I'll merge tomorrow unless I hear an objection. Thank you!

**Comment by snoyberg** [comment]
Thanks!

**Comment by gregwebs** [comment]
This seems to be missing the ability to use a section parameter. The [located-monad-logger package exports functions for this](
https://github.com/MailOnline/located-monad-logger/blob/master/src/Control/Monad/Logger/Located.hs).

**Pull request merged**
