### PR TITLE
Added query string to path logged by ApacheLogger

### LINKED ISSUE #139: Why apache logger uses only path?
By default Apache uses `%r` in it's format which means "First line of request" and `wai-logger` outputs only `rawPathInfo req` at that position i.e. omitting query string. Is it some deliberate decision?
Query string could be quite important for dubugging.

### PR DESCRIPTION
**Pull request by qrilka**
Fixes #139

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
Merged. Thank you for your contribution!

**Comment by qrilka** [comment]
@kazu-yamamoto @snoyberg this was merged half a year ago and Hackage show `wai-logger` version only from 2016 - are there any plans for a new release?

**Comment by snoyberg** [comment]
@kazu-yamamoto Ball's in your court on that one :)

**Comment by kazu-yamamoto** [comment]
I'm very sorry. I will release wai-logger tomorrow.

**Comment by kazu-yamamoto** [comment]
wai-logger 2.3.1 has been released.

**Pull request merged**
