### PR TITLE
drop unused blaze-builder dependency for wai-logger

### PR DESCRIPTION
**Pull request by mgmeier**

### CODE REVIEW

**Comment by mgmeier** [comment]
Just pointing out that the Travis fail is caused by the `monad-logger` package, which has nothing to do with this PR.

In the Travis log you can clearly see the line
`Installed wai-logger-2.3.2`
which means, all is good as far as this PR is concerned.

**Comment by kazu-yamamoto** [comment]
@mgmeier Thank you for this PR. I think that this should a major release, ie 2.4. Do you agree?

**Comment by kazu-yamamoto** [comment]
@mgmeier Never mind. I forgot that `blaze-builder` re-exports `Builder` of `bytestring`. Your PR is perfect.

**Comment by kazu-yamamoto** [comment]
Merged and released. Thank you for your contribution!

**Pull request merged**
